# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 05:52
from __future__ import unicode_literals

from django.db import migrations
import django_pg.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AddField(
            model_name='place',
            name='scores',
            field=django_pg.models.fields.json.JSONField(blank=True, default=[], null=True),
        ),
    ]
