# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_pg.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161025_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('image_1', models.FileField(blank=True, null=True, upload_to='events/image')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='events/image')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_day', models.DateField(blank=True, null=True, verbose_name='Dia inicio')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name='Dia fin')),
                ('start_hour', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('end_hour', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('min_price', models.FloatField(blank=True, default=0.0)),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratis')),
                ('prices', models.TextField(blank=True, verbose_name='Descripcion de los precios')),
                ('for_child', models.BooleanField(default=False)),
                ('for_teen', models.BooleanField(default=False)),
                ('for_adult', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('scores', django_pg.models.fields.json.JSONField(blank=True, default=[], null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Category')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Place')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
