# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-25 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='scores',
        ),
    ]
