# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-25 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20161125_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Empresa privada',
                'verbose_name_plural': 'Empresas privadas',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.CharField(help_text='Lunes 01 Nov - Jueves 31 Dic 2016', max_length=500, verbose_name='Fechas del cupon')),
                ('image', models.ImageField(upload_to='coupons/images', verbose_name='Imagen del cupon')),
                ('description', models.TextField(blank=True, verbose_name='Detalle del cupon')),
                ('code', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='coupons/qrs')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='terminos y condiciones')),
                ('q_1', models.CharField(max_length=300, verbose_name='Pregunta 1')),
                ('a_1', models.BooleanField(verbose_name='Respuesta 1')),
                ('q_2', models.CharField(max_length=300, verbose_name='Pregunta 2')),
                ('a_2', models.BooleanField(verbose_name='Respuesta 2')),
                ('q_3', models.CharField(max_length=300, verbose_name='Pregunta 3')),
                ('a_3', models.BooleanField(verbose_name='Respuesta 3')),
                ('q_4', models.CharField(max_length=300, verbose_name='Pregunta 4')),
                ('a_4', models.BooleanField(verbose_name='Respuesta 4')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.Company', verbose_name='Empresa Privada')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='events.Event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='coupons_user/qrs')),
                ('used', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_user', to='coupons.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupon Usuario',
                'verbose_name_plural': 'Cupones Usuario',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(related_name='coupons', through='coupons.CouponUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='couponuser',
            unique_together=set([('user', 'coupon')]),
        ),
    ]
