# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20161125_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='a_2',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='a_3',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='a_4',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='a_1',
            field=models.BooleanField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='q_1',
            field=models.CharField(max_length=300, verbose_name='Opcion 1'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='q_2',
            field=models.CharField(max_length=300, verbose_name='Opcion 2'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='q_3',
            field=models.CharField(max_length=300, verbose_name='Opcion 3'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='q_4',
            field=models.CharField(max_length=300, verbose_name='Opcion 4'),
        ),
    ]
