# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20161129_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='a_1',
            field=models.PositiveIntegerField(default=1, verbose_name='Respuesta'),
        ),
    ]
