# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20161129_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='question',
            field=models.CharField(default='', max_length=500, verbose_name='Pregunta'),
        ),
    ]
