# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-28 01:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='places',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
